<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-10-26 at 20:25:01.
 */
class PermissionTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Permission
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Permission;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Permission::authorize
     * @todo   Implement testAuthorize().
     */
    public function testAuthorize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Permission::isUser
     * @todo   Implement testIsUser().
     */
    public function testIsUser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Permission::inRole
     * @todo   Implement testInRole().
     */
    public function testInRole() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
